services:
  dashboard:
    image: ghcr.io/markis/hass-dashboard:latest
    container_name: hass-dashboard
    build:
      context: .
      dockerfile: Containerfile
    volumes:
      - ./config.yaml:/app/config.yaml:ro
      - ./output:/output
