version: "3.9"

services:
  dashboard:
    image: markis/hass-dashboard:latest
    container_name: dashboard
    env_file: .env
    build:
      context: .
      dockerfile: Containerfile
    volumes:
      - ./:/src
